"use client";
import { use, useState, useEffect } from "react";
import { PageShell } from "@/components/layout/PageShell";
import Link from "next/link";
import { ArrowLeft, Download, RefreshCw } from "lucide-react";

interface Brief {
  title: string;
  tldr: string;
  paragraphs: string[];
  pullQuote: string;
  citations: Array<{ paragraphIndex: number; diffId: string; signalId: string }>;
}

export default function BriefPage({ params }: { params: Promise<{ id: string }> }) {
  const { id: watchlistId } = use(params);
  const [brief, setBrief] = useState<Brief | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");

  const load = async () => {
    setLoading(true);
    setError("");
    try {
      const res = await fetch(`/api/brief?watchlistId=${watchlistId}`, { method: "POST" });
      if (!res.ok) throw new Error(`${res.status}`);
      const data = await res.json() as Brief;
      setBrief(data);
    } catch (err) {
      setError(err instanceof Error ? err.message : "Failed to generate brief");
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => { load(); }, [watchlistId]);

  return (
    <PageShell>
      <div className="max-w-3xl mx-auto">
        <div className="mb-8 flex items-center justify-between">
          <Link href={`/watchlists/${watchlistId}`} className="flex items-center gap-1.5 text-xs text-[oklch(0.45_0_0)] hover:text-[oklch(0.65_0_0)] transition-colors">
            <ArrowLeft size={12} /> Back to dashboard
          </Link>
          <div className="flex items-center gap-2">
            {!loading && (
              <button onClick={load} className="flex items-center gap-1.5 px-3 py-1.5 rounded-md text-xs border border-[oklch(0.28_0_0)] text-[oklch(0.55_0_0)] hover:bg-[oklch(0.17_0_0)] transition-colors">
                <RefreshCw size={11} /> Regenerate
              </button>
            )}
            <button onClick={() => window.print()} className="flex items-center gap-1.5 px-3 py-1.5 rounded-md text-xs border border-[oklch(0.28_0_0)] text-[oklch(0.65_0_0)] hover:bg-[oklch(0.17_0_0)] transition-colors">
              <Download size={12} /> PDF
            </button>
          </div>
        </div>

        {loading && (
          <div className="flex flex-col items-center justify-center py-24 text-center">
            <div className="w-10 h-10 rounded-full border-2 border-[oklch(0.25_0_0)] border-t-[oklch(0.72_0.16_240)] animate-spin mb-5" />
            <div className="text-sm font-semibold text-[oklch(0.70_0_0)]">Gemini is writing your brief...</div>
            <div className="text-xs text-[oklch(0.40_0_0)] mt-1">Analysing competitor landscape · ~15 seconds</div>
          </div>
        )}

        {error && !loading && (
          <div className="p-5 rounded-xl border border-[oklch(0.68_0.24_25/0.3)] bg-[oklch(0.68_0.24_25/0.06)] text-center">
            <div className="text-sm font-semibold text-[oklch(0.68_0.24_25)] mb-2">Failed to generate</div>
            <div className="text-xs text-[oklch(0.55_0_0)] mb-4">{error}</div>
            <button onClick={load} className="text-xs text-[oklch(0.72_0.16_240)] hover:underline">Try again →</button>
          </div>
        )}

        {brief && !loading && (
          <>
            <h1 className="text-3xl font-bold leading-tight mb-4">{brief.title}</h1>

            {brief.tldr && (
              <div className="p-4 rounded-lg bg-[oklch(0.17_0_0)] border border-[oklch(0.22_0_0)] mb-6">
                <div className="text-[10px] font-mono text-[oklch(0.45_0_0)] uppercase mb-1.5">TL;DR</div>
                <p className="text-sm font-medium text-[oklch(0.85_0_0)] leading-relaxed">{brief.tldr}</p>
              </div>
            )}

            {brief.pullQuote && (
              <div className="border-l-4 border-[oklch(0.72_0.16_240)] pl-5 my-8">
                <p className="text-xl font-semibold text-[oklch(0.96_0_0)] leading-snug italic">
                  &ldquo;{brief.pullQuote}&rdquo;
                </p>
              </div>
            )}

            <div className="space-y-5">
              {brief.paragraphs?.map((para, i) => (
                <p key={i} className="text-[oklch(0.75_0_0)] leading-[1.85] text-base">{para}</p>
              ))}
            </div>

            <div className="mt-8 pt-6 border-t border-[oklch(0.22_0_0)] flex items-center justify-between text-[10px] font-mono text-[oklch(0.35_0_0)]">
              <span>Generated by Tower AI · Gemini 3.1 Flash</span>
              <span>{new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" })}</span>
            </div>
          </>
        )}
      </div>
    </PageShell>
  );
}
